services:
  webapp:
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
      HUGGINGFACE_API_TOKEN: ${HUGGINGFACE_API_TOKEN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    dns:
      - 8.8.8.8
      - 8.8.4.4

  database:
    build:
      context: ./database
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_URL: ${DATABASE_URL}

  nginx:
    build:
      context:
        ./nginx
    ports:
       - "80:80"
    depends_on:
      - webapp

volumes:
  db:
