services:
  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
      HUGGINGFACE_API_TOKEN: ${HUGGINGFACE_API_TOKEN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  database:
    build:
      context: ./database
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
    restart: unless-stopped

volumes:
  db:
